### ISSUE TITLE
Markdown internal anchor links support

### ISSUE THREAD

**Issue by XueK66** [MCDReforged/website#3]
网站里的插件的README中的内链跳转不生效

示例: https://mcdreforged.com/en/plugin/gugubot/readme (目录部分)
参见: https://gist.github.com/asabaylus/3071099

例子如下：
# 目录
- [目录](#目录)
- [config](#config)

# config
具体的config信息

发现者: @Seungmin922

**Comment by Fallen-Breath** [comment]
已知问题，暂不支持 GitHub markdown 的完整特性
